#!/bin/bash
#
# System tuning script for low-latency trading
# Run with sudo: sudo ./scripts/tune-system.sh
#

set -e

echo "=============================================="
echo "POLYMARKET ARB BOT - SYSTEM TUNING"
echo "=============================================="

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: Please run as root (sudo ./scripts/tune-system.sh)"
    exit 1
fi

echo ""
echo "1. Tuning network stack..."

# Increase socket buffer sizes
sysctl -w net.core.rmem_max=16777216
sysctl -w net.core.wmem_max=16777216
sysctl -w net.core.rmem_default=1048576
sysctl -w net.core.wmem_default=1048576

# TCP buffer sizes (min, default, max)
sysctl -w net.ipv4.tcp_rmem="4096 1048576 16777216"
sysctl -w net.ipv4.tcp_wmem="4096 1048576 16777216"

# Enable TCP_NODELAY behavior at kernel level
sysctl -w net.ipv4.tcp_low_latency=1

# Connection handling
sysctl -w net.core.somaxconn=65535
sysctl -w net.ipv4.tcp_max_syn_backlog=65535

# TCP keepalive (detect dead connections faster)
sysctl -w net.ipv4.tcp_keepalive_time=60
sysctl -w net.ipv4.tcp_keepalive_intvl=10
sysctl -w net.ipv4.tcp_keepalive_probes=6

# TCP fastopen
sysctl -w net.ipv4.tcp_fastopen=3

# Reduce TIME_WAIT
sysctl -w net.ipv4.tcp_fin_timeout=15
sysctl -w net.ipv4.tcp_tw_reuse=1

echo "   Network stack tuned."

echo ""
echo "2. Tuning file descriptor limits..."

# Get current user
CURRENT_USER=${SUDO_USER:-$USER}

# Check current limits
CURRENT_LIMIT=$(su - "$CURRENT_USER" -c "ulimit -n" 2>/dev/null || echo "1024")
echo "   Current limit: $CURRENT_LIMIT"

# Set new limits
if [ "$CURRENT_LIMIT" -lt 65535 ]; then
    echo "   Setting new limits..."

    # Add to limits.conf if not already there
    if ! grep -q "nofile 65535" /etc/security/limits.conf; then
        echo "* soft nofile 65535" >> /etc/security/limits.conf
        echo "* hard nofile 65535" >> /etc/security/limits.conf
        echo "   Added to /etc/security/limits.conf"
    fi

    # Also set for systemd services
    if [ -d /etc/systemd/system.conf.d ]; then
        mkdir -p /etc/systemd/system.conf.d
        echo "[Manager]" > /etc/systemd/system.conf.d/limits.conf
        echo "DefaultLimitNOFILE=65535" >> /etc/systemd/system.conf.d/limits.conf
        echo "   Configured systemd limits"
    fi
fi

echo ""
echo "3. Saving settings for persistence..."

# Write to sysctl.conf for persistence
SYSCTL_CONF="/etc/sysctl.d/99-polymarket-arb.conf"
cat > "$SYSCTL_CONF" << 'EOF'
# Polymarket Arbitrage Bot - Network Tuning
# Generated by tune-system.sh

# Socket buffer sizes
net.core.rmem_max=16777216
net.core.wmem_max=16777216
net.core.rmem_default=1048576
net.core.wmem_default=1048576

# TCP buffer sizes
net.ipv4.tcp_rmem=4096 1048576 16777216
net.ipv4.tcp_wmem=4096 1048576 16777216

# Low latency
net.ipv4.tcp_low_latency=1

# Connection handling
net.core.somaxconn=65535
net.ipv4.tcp_max_syn_backlog=65535

# TCP keepalive
net.ipv4.tcp_keepalive_time=60
net.ipv4.tcp_keepalive_intvl=10
net.ipv4.tcp_keepalive_probes=6

# TCP fastopen
net.ipv4.tcp_fastopen=3

# TIME_WAIT optimization
net.ipv4.tcp_fin_timeout=15
net.ipv4.tcp_tw_reuse=1
EOF

echo "   Saved to $SYSCTL_CONF"

echo ""
echo "=============================================="
echo "SYSTEM TUNING COMPLETE"
echo ""
echo "Note: Some changes require a reboot to take effect."
echo "Run 'sudo sysctl -p $SYSCTL_CONF' to apply now."
echo "=============================================="
